SistemaBancoDeSangre/Models/ControlDonaciones.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SistemaBancoDeSangre.Models
{
    public class ControlDonaciones
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "Donante")]
        public int DonanteId { get; set; }  // Cambié esto para que se guarde el ID del Donante

        [Required]
        [Display(Name = "Centro De Donacion")]
        public int CentroDonacionId { get; set; }  // Cambié esto para que se guarde el ID del Centro de Donación

        [Required]
        [Display(Name = "Fecha de Donacion")]
        [DataType(DataType.Date)]
        
        public DateTime FechaDonacion { get; set; }

        // Relaciones
        public Donante Donante { get; set; }

        [Display(Name = "Nombre Centro Donación")]
        public CentroDonacion CentroDonacion { get; set; }
    }
}

SistemaBancoDeSangre/Controllers/ControlDonacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaBancoDeSangre.Data;
using SistemaBancoDeSangre.Models;

namespace SistemaBancoDeSangre.Controllers
{
    public class ControlDonacionesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ControlDonacionesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ControlDonaciones
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ControlDonaciones.Include(c => c.CentroDonacion).Include(c => c.Donante);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ControlDonaciones/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var controlDonaciones = await _context.ControlDonaciones
                .Include(c => c.CentroDonacion)
                .Include(c => c.Donante)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (controlDonaciones == null)
            {
                return NotFound();
            }

            return View(controlDonaciones);
        }

        // GET: ControlDonaciones/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["CentroDonacionId"] = new SelectList(_context.CentroDonacion, "ID", "NombreCentro");
            ViewData["DonanteId"] = new SelectList(_context.Donante, "Id", "NombreCompleto");
            return View();
        }


        // POST: ControlDonaciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("ID,DonanteId,CentroDonacionId,FechaDonacion")] ControlDonaciones controlDonaciones)
        {
            if (ModelState.IsValid)
            {
                _context.Add(controlDonaciones);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CentroDonacionId"] = new SelectList(_context.CentroDonacion, "ID", "NombreCentro", controlDonaciones.CentroDonacionId);
            ViewData["DonanteId"] = new SelectList(_context.Donante, "Id", "GrupoSanguineo", controlDonaciones.DonanteId);
            return View(controlDonaciones);
        }

        // GET: ControlDonaciones/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var controlDonaciones = await _context.ControlDonaciones.FindAsync(id);
            if (controlDonaciones == null)
            {
                return NotFound();
            }
            ViewData["CentroDonacionId"] = new SelectList(_context.CentroDonacion, "ID", "NombreCentro", controlDonaciones.CentroDonacionId);
            ViewData["DonanteId"] = new SelectList(_context.Donante, "Id", "GrupoSanguineo", controlDonaciones.DonanteId);
            return View(controlDonaciones);
        }

        // POST: ControlDonaciones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ID,DonanteId,CentroDonacionId,FechaDonacion")] ControlDonaciones controlDonaciones)
        {
            if (id != controlDonaciones.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(controlDonaciones);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ControlDonacionesExists(controlDonaciones.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CentroDonacionId"] = new SelectList(_context.CentroDonacion, "ID", "NombreCentro", controlDonaciones.CentroDonacionId);
            ViewData["DonanteId"] = new SelectList(_context.Donante, "Id", "GrupoSanguineo", controlDonaciones.DonanteId);
            return View(controlDonaciones);
        }

        // GET: ControlDonaciones/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var controlDonaciones = await _context.ControlDonaciones
                .Include(c => c.CentroDonacion)
                .Include(c => c.Donante)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (controlDonaciones == null)
            {
                return NotFound();
            }

            return View(controlDonaciones);
        }

        // POST: ControlDonaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var controlDonaciones = await _context.ControlDonaciones.FindAsync(id);
            _context.ControlDonaciones.Remove(controlDonaciones);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ControlDonacionesExists(int id)
        {
            return _context.ControlDonaciones.Any(e => e.ID == id);
        }
    }
}

SistemaBancoDeSangre/Views/ControlDonaciones/Create.cshtml
@model SistemaBancoDeSangre.Models.ControlDonaciones

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

   <h1>Registre nueva Donación</h1>

    <h4>ControlDonaciones</h4>
    
   



<hr />
<div class="row">
    <div class="col-md-4 ">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DonanteId" class="control-label"></label>
                <select asp-for="DonanteId" class ="form-control" asp-items="ViewBag.DonanteId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CentroDonacionId" class="control-label"></label>
                <select asp-for="CentroDonacionId" class ="form-control" asp-items="ViewBag.CentroDonacionId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaDonacion" class="control-label"></label>
                <input asp-for="FechaDonacion" class="form-control" />
                <span asp-validation-for="FechaDonacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="Index">Ir a la lista de Centro de donaciones</a>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaBancoDeSangre/Views/ControlDonaciones/CreateHome.cshtml
@model SistemaBancoDeSangre.Models.ControlDonaciones

@{
    ViewData["Title"] = "Create";
}

<h1>Crear nuevo</h1>

<h4>Control de donaciones</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DonanteId" class="control-label"></label>
                <select asp-for="DonanteId" class ="form-control" asp-items="ViewBag.DonanteId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CentroDonacionId" class="control-label"></label>
                <select asp-for="CentroDonacionId" class ="form-control" asp-items="ViewBag.CentroDonacionId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaDonacion" class="control-label"></label>
                <input asp-for="FechaDonacion" class="form-control" />
                <span asp-validation-for="FechaDonacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="ControlDonaciones" asp-action="Index">Regresar a la lista de Centro de donaciones</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaBancoDeSangre/Views/ControlDonaciones/Delete.cshtml
@model SistemaBancoDeSangre.Models.ControlDonaciones

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<h3>Estás seguro que deseas eliminar este Registro?</h3>
<div>
    <h4>ControlDonaciones</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDonacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDonacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Donante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Donante.GrupoSanguineo)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CentroDonacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CentroDonacion.NombreCentro)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SistemaBancoDeSangre/Views/ControlDonaciones/Details.cshtml
@model SistemaBancoDeSangre.Models.ControlDonaciones

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles</h1>

<div>
    <h4>Control de Donaciones</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDonacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDonacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Donante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Donante.GrupoSanguineo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CentroDonacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CentroDonacion.NombreCentro)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Regresar a la Lista de Centro de Donaciones</a>
</div>

SistemaBancoDeSangre/Views/ControlDonaciones/Edit.cshtml
@model SistemaBancoDeSangre.Models.ControlDonaciones

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Formulario de Edición</h1>

<h4>Centro de Donaciones</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="DonanteId" class="control-label"></label>
                <select asp-for="DonanteId" class="form-control" asp-items="ViewBag.DonanteId"></select>
                <span asp-validation-for="DonanteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CentroDonacionId" class="control-label"></label>
                <select asp-for="CentroDonacionId" class="form-control" asp-items="ViewBag.CentroDonacionId"></select>
                <span asp-validation-for="CentroDonacionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDonacion" class="control-label"></label>
                <input asp-for="FechaDonacion" class="form-control" />
                <span asp-validation-for="FechaDonacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista de Centro de Donaciones</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaBancoDeSangre/Views/ControlDonaciones/Index.cshtml
@model IEnumerable<SistemaBancoDeSangre.Models.ControlDonaciones>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Centro de donaciones</h1>

<p>
    <a asp-action="Create">Crear nuevo centro de donaciones.</a>
</p>
@if (!Model.Any())
{
    <div class="alert alert-warning" role="alert">
        No hay registros de donaciones disponibles.
    </div>
}else{
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FechaDonacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Donante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CentroDonacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDonacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Donante.GrupoSanguineo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CentroDonacion.NombreCentro)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Ver detalle</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>
}